spring:
  application.name=taxi-tracker
  data.mongodb.uri=mongodb://localhost:27017/taxitracker

events:
  queues:
    taxi.event.sqs.url: https://url-to-the-real-queue

aws:
  accessKeyId: noop
  secretAccessKey: noop
